# Generated by Django 3.2.12 on 2022-05-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeb',
            name='nameCount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='freeb',
            name='nameTOname',
            field=models.TextField(null=True),
        ),
    ]
