# Generated by Django 3.2.12 on 2022-05-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0002_auto_20220522_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nameINIT',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='freeb',
            name='nameINIT',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
