# Generated by Django 3.2.12 on 2022-05-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectureboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
