# Generated by Django 3.2.12 on 2022-05-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureboard', '0002_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureb',
            name='nameCount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lectureb',
            name='nameINIT',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lectureb',
            name='nameTOname',
            field=models.TextField(null=True),
        ),
    ]
