# Generated by Django 3.2.12 on 2022-05-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectureboard', '0003_auto_20220522_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureb',
            name='nameCount',
        ),
        migrations.RemoveField(
            model_name='lectureb',
            name='nameINIT',
        ),
        migrations.RemoveField(
            model_name='lectureb',
            name='nameTOname',
        ),
    ]
