# Generated by Django 3.2.12 on 2022-05-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionboard', '0002_alter_questionb_titleq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionb',
            name='titleQ',
            field=models.CharField(choices=[('미선택', '미선택'), ('고전역학', '고전역학'), ('응용물리탐구', '응용물리탐구'), ('프로그래밍', '프로그래밍'), ('수학세미나', '수학세미나'), ('통합수학', '통합수학'), ('에너지환경과학', '에너지환경과학')], max_length=200),
        ),
    ]
