# Generated by Django 3.2.12 on 2022-05-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionboard', '0003_alter_questionb_titleq'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionb',
            name='nameCount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionb',
            name='nameINIT',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questionb',
            name='nameTOname',
            field=models.TextField(null=True),
        ),
    ]
